#!/usr/bin/env python3
"""
Plot EKF Covariance Data

This script reads the CSV file generated by the local_submap_generator
and plots the robot pose covariance over time.

Usage:
    python3 plot_covariance.py [path_to_csv]

If no path is provided, defaults to: ./submaps/tb3_1/ekf_covariance.csv
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
import os


def plot_covariance(csv_file):
    """
    Plot covariance data from CSV file.

    Args:
        csv_file: Path to CSV file containing covariance data
    """
    if not os.path.exists(csv_file):
        print(f"Error: File not found: {csv_file}")
        return

    # Read CSV
    print(f"Reading data from: {csv_file}")
    df = pd.read_csv(csv_file)

    print(f"Loaded {len(df)} data points")
    print(f"Time range: {df['timestamp'].min():.2f}s to {df['timestamp'].max():.2f}s")
    print(f"Duration: {df['timestamp'].max() - df['timestamp'].min():.2f}s")

    # Create figure with subplots
    fig, axes = plt.subplots(3, 2, figsize=(14, 10))
    fig.suptitle('EKF Robot Pose Covariance Over Time', fontsize=16, fontweight='bold')

    # Time relative to start
    time = df['timestamp'] - df['timestamp'].min()

    # 1. Position Uncertainty (std_x, std_y)
    ax1 = axes[0, 0]
    ax1.plot(time, df['std_x'], label='σ_x', linewidth=2, color='blue')
    ax1.plot(time, df['std_y'], label='σ_y', linewidth=2, color='green')
    ax1.fill_between(time, 0, df['std_x'], alpha=0.2, color='blue')
    ax1.fill_between(time, 0, df['std_y'], alpha=0.2, color='green')
    ax1.set_xlabel('Time (s)')
    ax1.set_ylabel('Position Std Dev (m)')
    ax1.set_title('Position Uncertainty (X & Y)')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # 2. Orientation Uncertainty (std_theta)
    ax2 = axes[0, 1]
    ax2.plot(time, np.degrees(df['std_theta']), label='σ_θ', linewidth=2, color='red')
    ax2.fill_between(time, 0, np.degrees(df['std_theta']), alpha=0.2, color='red')
    ax2.set_xlabel('Time (s)')
    ax2.set_ylabel('Orientation Std Dev (°)')
    ax2.set_title('Orientation Uncertainty')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    # 3. Combined Position Uncertainty
    ax3 = axes[1, 0]
    ax3.plot(time, df['pos_uncertainty'], linewidth=2, color='purple')
    ax3.fill_between(time, 0, df['pos_uncertainty'], alpha=0.3, color='purple')
    ax3.set_xlabel('Time (s)')
    ax3.set_ylabel('Position Uncertainty (m)')
    ax3.set_title('Combined Position Uncertainty (√(σ_x² + σ_y²))')
    ax3.grid(True, alpha=0.3)

    # 4. Active Landmarks
    ax4 = axes[1, 1]
    ax4.plot(time, df['active_landmarks'], linewidth=2, color='orange', marker='o', markersize=3)
    ax4.fill_between(time, 0, df['active_landmarks'], alpha=0.3, color='orange')
    ax4.set_xlabel('Time (s)')
    ax4.set_ylabel('Number of Landmarks')
    ax4.set_title('Active Landmarks in State Vector')
    ax4.grid(True, alpha=0.3)

    # 5. Variances (cov_x, cov_y, cov_theta)
    ax5 = axes[2, 0]
    ax5.plot(time, df['cov_x'], label='Var(x)', linewidth=2, color='blue', alpha=0.7)
    ax5.plot(time, df['cov_y'], label='Var(y)', linewidth=2, color='green', alpha=0.7)
    ax5.set_xlabel('Time (s)')
    ax5.set_ylabel('Variance (m²)')
    ax5.set_title('Position Variances')
    ax5.legend()
    ax5.grid(True, alpha=0.3)

    # 6. State Size
    ax6 = axes[2, 1]
    ax6.plot(time, df['state_size'], linewidth=2, color='brown', marker='s', markersize=3)
    ax6.fill_between(time, 0, df['state_size'], alpha=0.3, color='brown')
    ax6.set_xlabel('Time (s)')
    ax6.set_ylabel('State Vector Size')
    ax6.set_title('EKF State Vector Size (Robot + Landmarks)')
    ax6.grid(True, alpha=0.3)

    plt.tight_layout()

    # Save figure
    output_file = csv_file.replace('.csv', '_plot.png')
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\nPlot saved to: {output_file}")

    # Show plot
    plt.show()

    # Print statistics
    print("\n" + "="*70)
    print("STATISTICS")
    print("="*70)
    print(f"Position Uncertainty:")
    print(f"  Initial: {df['pos_uncertainty'].iloc[0]:.4f} m")
    print(f"  Final:   {df['pos_uncertainty'].iloc[-1]:.4f} m")
    print(f"  Min:     {df['pos_uncertainty'].min():.4f} m")
    print(f"  Max:     {df['pos_uncertainty'].max():.4f} m")
    print(f"  Mean:    {df['pos_uncertainty'].mean():.4f} m")

    print(f"\nOrientation Uncertainty:")
    print(f"  Initial: {np.degrees(df['orient_uncertainty'].iloc[0]):.2f}°")
    print(f"  Final:   {np.degrees(df['orient_uncertainty'].iloc[-1]):.2f}°")
    print(f"  Min:     {np.degrees(df['orient_uncertainty'].min()):.2f}°")
    print(f"  Max:     {np.degrees(df['orient_uncertainty'].max()):.2f}°")
    print(f"  Mean:    {np.degrees(df['orient_uncertainty'].mean()):.2f}°")

    print(f"\nLandmarks:")
    print(f"  Max active:      {df['active_landmarks'].max()}")
    print(f"  Total updates:   {df['landmark_updates'].max()}")
    print(f"  Total obs:       {df['total_landmark_obs'].max()}")

    print(f"\nState Vector:")
    print(f"  Initial size:    {df['state_size'].iloc[0]}")
    print(f"  Final size:      {df['state_size'].iloc[-1]}")
    print(f"  Max size:        {df['state_size'].max()}")
    print("="*70)


def main():
    # Default path
    default_path = './submaps/tb3_1/ekf_covariance.csv'

    # Get path from command line or use default
    if len(sys.argv) > 1:
        csv_file = sys.argv[1]
    else:
        csv_file = default_path
        print(f"No file specified, using default: {csv_file}")

    plot_covariance(csv_file)


if __name__ == '__main__':
    main()
